In [51]:
import warnings 
warnings.filterwarnings('ignore')

In [52]:
import numpy as np

# creating dataset
docs = ["I love deep learning",
        "NLP is awesome",
        "Recurrent neural networks have memory"]

In [53]:
# applying tokenization on words (each word will be converted into a different number)
from keras.layers import TextVectorization

vectorizer = TextVectorization(output_mode='int')
vectorizer.adapt(docs)

vectorized_text = vectorizer(docs)

In [54]:
print(vectorized_text)

tf.Tensor(
[[10  7 12  8  0]
 [ 3  9 13  0  0]
 [ 2  4  5 11  6]], shape=(3, 5), dtype=int64)


### Type 1

In [55]:
temp = vectorizer.get_vocabulary()
for i, word in enumerate(temp):
    print(f"{word} : {i}")

 : 0
[UNK] : 1
recurrent : 2
nlp : 3
neural : 4
networks : 5
memory : 6
love : 7
learning : 8
is : 9
i : 10
have : 11
deep : 12
awesome : 13


### Type 2

In [56]:
vectorizer = TextVectorization(output_mode='count')
vectorizer.adapt(docs)

vectorized_text2 = vectorizer(docs)

In [57]:
print(vectorized_text2)

tf.Tensor(
[[0 0 0 0 0 0 1 1 0 1 0 1 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 1]
 [0 1 0 1 1 1 0 0 0 0 1 0 0]], shape=(3, 13), dtype=int64)


In [58]:
for i, word in enumerate(vectorizer.get_vocabulary()):
    print(f"{word} : {i}")

[UNK] : 0
recurrent : 1
nlp : 2
neural : 3
networks : 4
memory : 5
love : 6
learning : 7
is : 8
i : 9
have : 10
deep : 11
awesome : 12


### Type 3

In [59]:
vectorizer = TextVectorization(output_mode="tf_idf")
vectorizer.adapt(docs)

vectorized_text3 = vectorizer(docs)

In [60]:
print(vectorized_text3.shape)
print()
print(vectorized_text3.numpy())

(3, 13)

[[0.         0.         0.         0.         0.         0.
  0.91629076 0.91629076 0.         0.91629076 0.         0.91629076
  0.        ]
 [0.         0.         0.91629076 0.         0.         0.
  0.         0.         0.91629076 0.         0.         0.
  0.91629076]
 [0.         0.91629076 0.         0.91629076 0.91629076 0.91629076
  0.         0.         0.         0.         0.91629076 0.
  0.        ]]


**Using tfidf will create sparsity in the dataset, i mean if there is only 2 words in a sentence but still there will be 13 features, rest 11 features will be 0. same issue with count. And using int, is not good coz, model will prioritize the word with highest number. To prevent these Embedding is used.**


**EMBEDDING : A word embedding is a dense, low-dimensional vector representation of text where words with similar meanings or semantic relationships are mapped to neighboring points in a continuous vector space. In Embedding all the values are non zeros, not like tfidf or count where some of the values are zeros.**

### Type 4 - Embeddings

In [61]:
from keras import layers

In [62]:
vectorizer = TextVectorization(output_mode='int')
vectorizer.adapt(docs)
vectorized_text = vectorizer(docs)

length = len(vectorizer.get_vocabulary())

embedding = layers.Embedding(input_dim=length, output_dim=4)

vectorized_text = embedding(vectorized_text)

In [63]:
print(vectorized_text.shape)
print()
print(vectorized_text)

(3, 5, 4)

tf.Tensor(
[[[ 0.03387661 -0.01730232  0.03645266 -0.04279417]
  [ 0.01965698  0.03569007 -0.00873654 -0.00119417]
  [ 0.0031765   0.00931216  0.01831918 -0.00907288]
  [-0.04610251 -0.04727364 -0.02800303 -0.04278932]
  [ 0.04183869  0.00575048 -0.02355027  0.0183526 ]]

 [[ 0.04520804 -0.01336712 -0.04176331  0.01774413]
  [-0.01853002  0.04360152  0.01768423 -0.01380855]
  [-0.03724599 -0.01583613  0.02203283  0.04011701]
  [ 0.04183869  0.00575048 -0.02355027  0.0183526 ]
  [ 0.04183869  0.00575048 -0.02355027  0.0183526 ]]

 [[-0.01803403 -0.01081818 -0.02672478  0.01808165]
  [ 0.0090818   0.01213788 -0.0042469   0.02675064]
  [ 0.04450632  0.02283369 -0.03121733  0.04236401]
  [-0.04173736 -0.02003615  0.01995358 -0.03452538]
  [ 0.00041525  0.02898819 -0.01086964 -0.04140973]]], shape=(3, 5, 4), dtype=float32)
