In [1]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
from datasets import load_dataset

dataset = load_dataset("roneneldan/TinyStories")

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…):   0%|          | 0.00/249M [00:00<?, ?B/s]

data/train-00001-of-00004-5852b56a2bd28f(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/train-00002-of-00004-a26307300439e9(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00003-of-00004-d243063613e5a0(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/validation-00000-of-00001-869c898b5(…):   0%|          | 0.00/9.99M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

In [3]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 2119719
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 21990
    })
})


In the above dictionary 'text' is an entire column that holds different rows of texts. And the numbers below it shows how many rows are there.

In [4]:
data = dataset['train']
print(data)

Dataset({
    features: ['text'],
    num_rows: 2119719
})


In [5]:
train = data['text']
print(len(train))

2119719


In [6]:
train[0:3]

['One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.\n\nLily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."\n\nTogether, they shared the needle and sewed the button on Lily\'s shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.',
 'Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel. Good fuel made Beep happy and strong.\n\nOne day, Beep was driving in the park when he saw a big tree. The tree had many leaves that we

In [11]:
tokenized_stories = [clean_text(story) for story in clean_stories]

In [12]:
word_counts = {}
for story in tokenized_stories:
    for word in story:
        word_counts[word] = word_counts.get(word, 0) + 1

In [17]:
list(word_counts.items())[:10]

[('one', 2052753),
 ('day', 2669157),
 ('a', 11475844),
 ('little', 1837809),
 ('girl', 1247008),
 ('named', 882811),
 ('lily', 2841916),
 ('found', 593044),
 ('needle', 13458),
 ('in', 3220276)]

In [25]:
sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

In [26]:
sorted_words[:10]

[('the', 20239129),
 ('and', 18112793),
 ('to', 12647809),
 ('a', 11475844),
 ('was', 9436556),
 ('he', 7955580),
 ('she', 7699184),
 ('they', 6754883),
 ('it', 6667637),
 ('her', 4921724)]

In [9]:
import string

In [11]:
for i in train:
    print(i)
    break

One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.

Lily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."

Together, they shared the needle and sewed the button on Lily's shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.


In [20]:
clean_stories = [story.strip() for story in train[:] if story.strip() != ""]

In [21]:
def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "",string.punctuation))
    return text.split()

str.maketrans(x, y, z)
This function creates a translation map (a dictionary of character mappings). It takes up to three arguments:

- x: Characters you want to replace.
- y: Characters you want to replace them with.
- z: Characters you want to delete entirely.

We pass empty strings "" for x and y because we do not want to replace any characters. We pass string.punctuation as the third parameter z because we want to delete all punctuations.

In [22]:
tokenization_stories = [clean_text(story) for story in clean_stories]

In [24]:
word_counts = {}
for story in tokenization_stories:
    for word in story:
        word_counts[word] = word_counts.get(word, 0) + 1

In [25]:
list(word_counts.items())[:10]

[('one', 2052753),
 ('day', 2669157),
 ('a', 11475844),
 ('little', 1837809),
 ('girl', 1247008),
 ('named', 882811),
 ('lily', 2841916),
 ('found', 593044),
 ('needle', 13458),
 ('in', 3220276)]

In [26]:
sorted_words = sorted(word_counts.items(), key=lambda x:x[1], reverse=True)

Based on the number of the word, the entire list of the words will be sorted.

In [27]:
sorted_words[:10]

[('the', 20239129),
 ('and', 18112793),
 ('to', 12647809),
 ('a', 11475844),
 ('was', 9436556),
 ('he', 7955580),
 ('she', 7699184),
 ('they', 6754883),
 ('it', 6667637),
 ('her', 4921724)]

In [28]:
len(sorted_words)

73128

In [29]:
vocab_size = 10000
top_words = [word for word, count in sorted_words[: vocab_size - 1]]

In [37]:
top_words[:10]

['the', 'and', 'to', 'a', 'was', 'he', 'she', 'they', 'it', 'her']

In [38]:
word2idx = {word: idx + 1 for idx, word in enumerate(top_words)}
word2idx["<UNK>"] = 0
idx2word = ["<UNK>"] + top_words

In [44]:
seq_len = 10

# 1. Define the sequences using your existing clean_text function
sequences = [[word2idx.get(w, 0) for w in clean_text(story)] for story in train[:2000]]

# 2. Generate the sliding window input sequences
input_sequences = [seq[i:i + seq_len + 1] for seq in sequences for i in range(len(seq) - seq_len)]

# 3. Create x and y
# x is the first seq_len tokens, y is the target (the next token)
input_data = np.array(input_sequences)
x, y = input_data[:, :-1], input_data[:, -1]

In [48]:
print(x)
print()
print()
print(y)

[[  25   20    4 ...  100    4 1787]
 [  20    4   29 ...    4 1787   12]
 [   4   29   45 ... 1787   12   10]
 ...
 [ 112  705 3806 ...    6    5  370]
 [ 705 3806  135 ...    5  370   18]
 [3806  135   14 ...  370   18  158]]


[ 12  10 176 ...  18 158  73]


In [50]:
import keras
from keras import layers, Sequential
from keras.layers import LSTM, Dense, Embedding

In [51]:
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=50, input_shape=(sequence_length,)),
    LSTM(128),
    Dense(vocab_size, activation='softmax')
])

I0000 00:00:1782111669.949738      58 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1782111669.955227      58 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


In [54]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 10, 50)         │       500,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 128)            │        91,648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10000)          │     1,290,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,881,648 (7.18 MB)

 Trainable params: 1,881,648 (7.18 MB)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [56]:
model.fit(x, y, epochs=10, batch_size=64)

Epoch 1/10


I0000 00:00:1782112217.028302    1430 cuda_dnn.cc:529] Loaded cuDNN version 91002


4863/4863 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - accuracy: 0.1236 - loss: 5.4290
Epoch 2/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.1994 - loss: 4.5031
Epoch 3/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.2280 - loss: 4.1635
Epoch 4/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.2475 - loss: 3.9465
Epoch 5/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.2639 - loss: 3.7806
Epoch 6/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - accuracy: 0.2762 - loss: 3.6450
Epoch 7/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.2880 - loss: 3.5275
Epoch 8/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.2980 - loss: 3.4251
Epoch 9/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.3064 - loss: 3.3343
Epoch 10/10
4863/4863 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.3159 - loss: 3.2508


In [57]:

def generate_text(seed_text, next_words=10):
    for _ in range(next_words):
        cleaned_seed = clean_text(seed_text)
        seed_seq = [word2idx.get(word, 0) for word in cleaned_seed]
        if len(seed_seq) < sequence_length:
            seed_seq = [0] * (sequence_length - len(seed_seq)) + seed_seq
        else:
            seed_seq = seed_seq[-sequence_length:]
        
        input_data = np.array([seed_seq])
        prediction = model.predict(input_data, verbose=0)
        predicted_idx = np.argmax(prediction, axis=-1)[0]
        predicted_word = idx2word[predicted_idx]
        seed_text += " " + predicted_word
    return seed_text

print(generate_text("once upon a time there was a little"))

once upon a time there was a little girl named lily she loved to play with her toys
