In [1]:
from datasets import load_dataset

In [2]:
dataset = load_dataset("ylacombe/english_dialects", "southern_male")

README.md: 0.00B [00:00, ?B/s]

southern_male/train-00000-of-00006-830c7(…):   0%|          | 0.00/348M [00:00<?, ?B/s]

southern_male/train-00001-of-00006-e6c32(…):   0%|          | 0.00/352M [00:00<?, ?B/s]

southern_male/train-00002-of-00006-d5554(…):   0%|          | 0.00/349M [00:00<?, ?B/s]

southern_male/train-00003-of-00006-1d94a(…):   0%|          | 0.00/350M [00:00<?, ?B/s]

southern_male/train-00004-of-00006-5eab6(…):   0%|          | 0.00/349M [00:00<?, ?B/s]

southern_male/train-00005-of-00006-e157c(…):   0%|          | 0.00/357M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4331 [00:00<?, ? examples/s]

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['line_id', 'audio', 'text', 'speaker_id'],
        num_rows: 4331
    })
})

In [4]:
dataset['train'][:5]

{'line_id': ['EN0787', 'EN0021', 'EN0770', 'EN0045', 'EN1033'],
 'audio': [<datasets.features._torchcodec.AudioDecoder at 0x79c395b055e0>,
 'text': ['The splendid fort with the awe-inspiring rock and the aesthetically fortified courts stir the imagination of tourists',
  'This is a very common type of bow one showing mainly red and yellow with little or no green or blue',
  'The second visual ends with a shot of the two hugging together',
  'Charles thought he could save on the air fare by charging the shipping fees to his employer',
  'Irish stepdance was popularized by the show Riverdance'],
 'speaker_id': [9799, 295, 295, 2121, 9334]}

In [5]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

In [6]:
data = pd.DataFrame()
data['text'] = dataset['train']['text']

In [7]:
print(data.shape)

for row in data['text'][:10]:
    print(row)

(4331, 1)
The splendid fort with the awe-inspiring rock and the aesthetically fortified courts stir the imagination of tourists
This is a very common type of bow one showing mainly red and yellow with little or no green or blue
The second visual ends with a shot of the two hugging together
Charles thought he could save on the air fare by charging the shipping fees to his employer
Irish stepdance was popularized by the show Riverdance
Here's one for the joystick generation
The rainbow is a division of white light into many beautiful colours
The width of the coloured band increases as the size of the drops increases
The events and characters of the Arthurian legend varies widely from text to text and there is no one canonical version
Northern Catalpa has a trunk up to one metre diameter


---

In [8]:
para = [
    ["".join(i.lower())] for i in data['text']
]

In [9]:
print(para[:5])

[['the splendid fort with the awe-inspiring rock and the aesthetically fortified courts stir the imagination of tourists'], ['this is a very common type of bow one showing mainly red and yellow with little or no green or blue'], ['the second visual ends with a shot of the two hugging together'], ['charles thought he could save on the air fare by charging the shipping fees to his employer'], ['irish stepdance was popularized by the show riverdance']]


In [10]:
import re
para = [[re.sub(r'[^\w\s]','',i)] for text in para[:5] for i in text]
print(len(para))
print(para)

5
[['the splendid fort with the aweinspiring rock and the aesthetically fortified courts stir the imagination of tourists'], ['this is a very common type of bow one showing mainly red and yellow with little or no green or blue'], ['the second visual ends with a shot of the two hugging together'], ['charles thought he could save on the air fare by charging the shipping fees to his employer'], ['irish stepdance was popularized by the show riverdance']]


---

### Storig all the row data from the dataset into a single obj

In [13]:
import re
para = [[sentence.lower()] for sentence in data['text']]
para = [[re.sub(r'[^\w\s]','',chars)] for sentence in para for chars in sentence]

In [14]:
print(len(para), '\n')
para[:10]

4331 



[['the splendid fort with the aweinspiring rock and the aesthetically fortified courts stir the imagination of tourists'],
 ['this is a very common type of bow one showing mainly red and yellow with little or no green or blue'],
 ['the second visual ends with a shot of the two hugging together'],
 ['charles thought he could save on the air fare by charging the shipping fees to his employer'],
 ['irish stepdance was popularized by the show riverdance'],
 ['heres one for the joystick generation'],
 ['the rainbow is a division of white light into many beautiful colours'],
 ['the width of the coloured band increases as the size of the drops increases'],
 ['the events and characters of the arthurian legend varies widely from text to text and there is no one canonical version'],
 ['northern catalpa has a trunk up to one metre diameter']]

In [15]:
print(para[:10])

[['the splendid fort with the aweinspiring rock and the aesthetically fortified courts stir the imagination of tourists'], ['this is a very common type of bow one showing mainly red and yellow with little or no green or blue'], ['the second visual ends with a shot of the two hugging together'], ['charles thought he could save on the air fare by charging the shipping fees to his employer'], ['irish stepdance was popularized by the show riverdance'], ['heres one for the joystick generation'], ['the rainbow is a division of white light into many beautiful colours'], ['the width of the coloured band increases as the size of the drops increases'], ['the events and characters of the arthurian legend varies widely from text to text and there is no one canonical version'], ['northern catalpa has a trunk up to one metre diameter']]


### Text Preprocessing : Converting the entire sentences into list of words

In [17]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import text_to_word_sequence

import re

In [21]:
for i in para[:5]:
    print(i[0])

the splendid fort with the aweinspiring rock and the aesthetically fortified courts stir the imagination of tourists
this is a very common type of bow one showing mainly red and yellow with little or no green or blue
the second visual ends with a shot of the two hugging together
charles thought he could save on the air fare by charging the shipping fees to his employer
irish stepdance was popularized by the show riverdance


In [23]:
para_preprocessed = [text_to_word_sequence(sentence[0]) for sentence in para]

In [25]:
para_preprocessed[:2]

[['the',
  'splendid',
  'fort',
  'with',
  'the',
  'aweinspiring',
  'rock',
  'and',
  'the',
  'aesthetically',
  'fortified',
  'courts',
  'stir',
  'the',
  'imagination',
  'of',
  'tourists'],
 ['this',
  'is',
  'a',
  'very',
  'common',
  'type',
  'of',
  'bow',
  'one',
  'showing',
  'mainly',
  'red',
  'and',
  'yellow',
  'with',
  'little',
  'or',
  'no',
  'green',
  'or',
  'blue']]

### Checking for total number of words

In [26]:
# words and their frequency
freq = {}

for sentence in para_preprocessed:
    for word in sentence:
        if word in freq:
            freq[word] += 1
        else:
            freq[word] = 1



In [31]:
# printing total number of words
print(len(freq))

# printing top 20 high frequency words
print(sorted(freq.items(), key=lambda x : x[1], reverse=True)[:20])

6762
[('the', 4107), ('to', 1738), ('of', 1644), ('a', 1567), ('and', 1468), ('in', 1078), ('is', 1042), ('from', 795), ('for', 534), ('with', 505), ('on', 483), ('at', 414), ('or', 401), ('as', 388), ('by', 374), ('it', 373), ('that', 370), ('are', 364), ('your', 347), ('was', 321)]


### Applying vectorization

### Approach 1 : Using `Tokenizer`

In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [33]:
tokenizer = Tokenizer(num_words=5000,oov_token="<UNK>")

tokenizer.fit_on_texts(para_preprocessed)
para_vectors = tokenizer.texts_to_sequences(para_preprocessed)

In [35]:
para_vectors[:2]

[[2,
  2168,
  1605,
  11,
  2,
  2169,
  1291,
  6,
  2,
  2170,
  2171,
  1606,
  1607,
  2,
  2172,
  4,
  307],
 [30,
  8,
  5,
  223,
  155,
  245,
  4,
  65,
  29,
  281,
  387,
  45,
  6,
  52,
  11,
  198,
  14,
  47,
  49,
  14,
  124]]

### Approach 2 : Using `TextVectorization`

In [36]:
from tensorflow.keras.layers import TextVectorization

Since TextVectorization only expects stirng, so we had to send `para` instead of `para_preprocessed` for `TextVectorization`

In [42]:
vectorizer = TextVectorization(max_tokens=5000)
vectorizer.adapt(para)
para_vector = vectorizer(para).numpy()

In [47]:
print(para_vector)
print()
print()
print(para_vector[:1])

[[   2 2516 1966 ...    0    0    0]
 [  30    8    5 ...    0    0    0]
 [   2  200  103 ...    0    0    0]
 ...
 [   2  543   47 ...    0    0    0]
 [   2  265    4 ...    0    0    0]
 [1459  225    6 ...    0    0    0]]


[[   2 2516 1966   11    2 4086 1361    6    2 4203 3493 2036 1689    2
  3325    4  310    0    0    0    0    0    0    0    0    0    0]]
