In [9]:
import numpy as np
import sys

In [10]:
a = np.array(range(0,30,2))
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [11]:
print(sys.getsizeof(a))      # taking 232 bytes

232


In [24]:
np.insert(a, -1, 999)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26, 999,  28])

In [25]:
np.append(a, 999)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28, 999])

In [26]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

---

In [33]:
b = np.array(['hii','ajs'])
b

array(['hii', 'ajs'], dtype='<U3')

In [36]:
np.insert(b, 1, 5)

array(['hii', '5', 'ajs'], dtype='<U3')

In [37]:
np.append(b, 10)

array(['hii', 'ajs', '10'], dtype='<U21')